### ISSUE TITLE
Color picker covered up

### ISSUE THREAD

**Issue by bubbleheadinc** [PeterStaev/nativescript-photo-editor#19]
Thanks for the plugin! Great work.

On iPhone X's, the color picker is covered half way by the keyboard when writing text and by the bottom of the screen when drawing. Is this due to the safe areas? Is there a way to fix this via {N} or styling?

Screenshots: 
![IMG_A2808134B0C5-1](https://user-images.githubusercontent.com/4236279/56142878-6dd10680-5f6d-11e9-99bc-d8916d0cf2b5.jpeg)
![IMG_9BA6D3C5C0F3-1](https://user-images.githubusercontent.com/4236279/56142879-6dd10680-5f6d-11e9-9e2f-9e8e5cbcb93d.jpeg)

**Comment by PeterStaev** [comment]
This is now fixed in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
