### ISSUE TITLE
iOS hiddenControls PhotoEditorControl.Text bug

### ISSUE THREAD

**Issue by ryandenvor** [PeterStaev/nativescript-photo-editor#27]
In iOS, passing PhotoEditorControl.Text in hiddenControls still displays the text editing option.

**Comment by PeterStaev** [comment]
This is now fixed in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
