### ISSUE TITLE
Hi, color picker is hidden by text keyboard on ios!

### ISSUE THREAD

**Issue by Woongsik** [PeterStaev/nativescript-photo-editor#31]
Thanks for the plug in, this is really nice!

I am having a trouble that color picker is hidden by keyboard on ios 13 (actually on iPhone X)

Any solution for this??

**Comment by PeterStaev** [comment]
Hey @Woongsik , this is already fixed in the [ProPlugins](https://proplugins.org) version of the plugin.  

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
