### ISSUE TITLE
ios invalid podfile 

### ISSUE THREAD

**Issue by nginx17** [PeterStaev/nativescript-photo-editor#9]
@PeterStaev i run tns run ios --bundle and i getting error 
`Invalid Podfile file: The target Pods-appname already has a platform set..`

if i remove this plugin and run ios my apps run fine

**Comment by PeterStaev** [comment]
Hey @nginx17 , this is because you have some other plugin installed that also defines a `platform` directive in its `Podfile`. Sadly no elegant solution to solve this, but to manually edit the in `platforms/ios/Podfile` and make sure there is a single line with `platform :ios` and that it defines at least version 9.0 which is required by this plugin. Also note that you will have to do this every time you clean your platforms 😢

**Comment by nginx17** [comment]
@PeterStaev ok i will try again
